# MZLA Notion Scripts Configuration
# See README for more information on the setup

[sync]

[sync.services]
method = "github_labels"
enabled = false # TODO Services needs to check if the new code works

# This is the ID of the All GitHub Issues database.
notion_tasks_id = "3ca7ed3fe75b4a6d805953156a603540"

# This is the ID of the Milestones database.
notion_milestones_id = "1352df5d45ae8068a42dc799f13ea87a"
strip_orgname = true

repositories = [
    "thunderbird/addons-server",
    "thunderbird/appointment",
    "thunderbird/assist",
    "thunderbird/cloudops",
    "thunderbird/code-coverage",
    "thunderbird/mailstrom",
    "thunderbird/notion-scripts",
    "thunderbird/pulumi",
    "thunderbird/send-suite",
    "thunderbird/services-ui",
    "thunderbird/services-utils",
    "thunderbird/stats",
    "thunderbird/thunderbird-accounts",
    "thunderbird/thunderbird-notifications",
    "thunderbird/thunderbird-website",
    "thunderbird/thunderblog",
    "thunderbird/thundernest-ansible",
    "thunderbird/knowledgebase-issues",
    "thunderbird/android-knowledgebase-issues",
    "thunderbird/tbpro-knowledgebase-issues",
    "thunderbird/zendesk-config"
]

[sync.mobile]
method = "github_project"
notion_tasks_id = "94ca27a3d7374a4fae6ad6d5c7a70a76"
notion_milestones_id = "637245a2c53b4d86a99c6e97006153df"
notion_sprints_id = "19e2df5d45ae803fa74ff4d6aa52f25f"

milestones_tracker_prefix = "[EPIC] "
milestones_github_label = "type: epic"
milestones_body_sync = false
milestones_body_sync_if_empty = true
tasks_body_sync = false
sprints_merge_by_name = true

[sync.mobile.properties]
notion_tasks_text_assignee = "GitHub Assignee"
notion_issue_field = "GitHub Issue"
notion_sprint_tracker_id = "GitHub ID"

[sync.mobile.repositories]

[sync.mobile.repositories.android]
repositories = [
  "thunderbird/thunderbird-android"
]
github_tasks_project_id = "PVT_kwDOAOe9Jc4AygBu"
github_milestones_project_id = "PVT_kwDOAOe9Jc4Ayf_S"

[sync.mobile.repositories.ios]
repositories = [
  "thunderbird/thunderbird-ios"
]
github_tasks_project_id = "PVT_kwDOAOe9Jc4A1aav"
github_milestones_project_id = "PVT_kwDOAOe9Jc4A1aX6"

[sync.bugzilla]
method = "bugzilla_project"
tracker_dry_run = true
notion_tasks_id = "20f2df5d45ae8004baeadc784d8f7ea4"
notion_milestones_id = "20f2df5d45ae80be9a0dc390d0ac50f4"
bugzilla_base = "https://bugzilla.mozilla.org"
milestones_tracker_prefix = "[meta] "

[sync.bugzilla.properties]
notion_tasks_title = "Name"
notion_issue_field = "Bugzilla Issue"
notion_milestones_title = "Name"
notion_tasks_milestone_relation = "Milestone"
notion_tasks_priority_values = ["P1", "P2", "P3", "P4", "P5"]
notion_tasks_assignee = "Assignee"
