# Development environment, for a personal Notion instance

[sync]

[sync.services]
method = "github_labels"
notion_tasks_id = "19ddea4adcdf8052906aeeb2f3d5acc9"
notion_milestones_id = "19ddea4adcdf8018b060cda446ff2835"
strip_orgname = true

repositories = [
  "kewisch/test"
]


[sync.mobile]
method = "github_project"
notion_tasks_id = "18adea4adcdf807c8fabcc9c11b61777"
notion_milestones_id = "18adea4adcdf80b9a9e0f3c1a18ede53"
notion_sprints_id = "18adea4adcdf8073af16f1d07eb1661e"

#milestones_body_sync = true
milestones_body_sync_if_empty = true
sprints_merge_by_name = true
milestones_github_label = "type: epic"

tasks_notion_prefix = "[GitHub] "

[sync.mobile.repositories]

[sync.mobile.repositories.test]
repositories = [
  "kewisch/test"
]
github_tasks_project_id = "PVT_kwHOAAlD3s4AxVFW"
github_milestones_project_id = "PVT_kwHOAAlD3s4AxVDI"

[sync.mobile.repositories.test2]
repositories = [
  "kewisch/test2"
]
github_tasks_project_id = "PVT_kwHOAAlD3s4A1bUZ"
github_milestones_project_id = "PVT_kwHOAAlD3s4A1bUn"

[sync.mobile.properties]
notion_tasks_title = "Title"
notion_tasks_assignee = "Assignee"
notion_tasks_dates = "Date"
notion_tasks_milestone_relation = "Project"
notion_milestones_title = "Name"
notion_milestones_assignee = "Assignee"
notion_tasks_open_state = "Not started"
notion_issue_field = "GitHub Issue"
notion_sprint_tracker_id = "GitHub ID"


[sync.bugzilla]
method = "bugzilla_project"
tracker_dry_run = true
notion_tasks_id = "20edea4adcdf80b782faf2011506f86e"
notion_milestones_id = "20edea4adcdf8064878af1281be913c8"
bugzilla_base = "https://bugzilla.mozilla.org"
milestones_tracker_prefix = "[meta] "

[sync.bugzilla.properties]
notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_milestones_title = "Name"
notion_issue_field = "Bugzilla Issue"
notion_tasks_milestone_relation = "Milestone"
notion_tasks_priority_values = ["P1", "P2", "P3", "P4", "P5"]
