---
name: CI

on:
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b  # v6.6.0
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-nothing-to-cache: true

      - name: uv sync
        run: uv sync

      - name: lint
        env:
          VERBOSE: ${{ runner.debug && '-v' || '' }}
        run:
          uv run task lint ${VERBOSE}

      - name: format
        env:
          VERBOSE: ${{ runner.debug && '-v' || '' }}
        run:
          uv run task format --check ${VERBOSE}

      - name: test
        env:
          VERBOSE: ${{ runner.debug && '-v' || '' }}
        run:
          uv run task test ${VERBOSE}
